version: "2.4"

x-var: &APP_IMAGE_TAG
  "my_app:1.0.0"
x-var: &RUBY_VERSION
  "2.7.0-slim-buster"
x-var: &NODE_MAJOR
  12
x-var: &YARN_VERSION
  1.21.1

x-app: &app
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile
    args:
      RUBY_VERSION: *RUBY_VERSION
      NODE_MAJOR: *NODE_MAJOR
      YARN_VERSION: *YARN_VERSION
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
  image: *APP_IMAGE_TAG
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - ./node_modules:/app/node_modules:cached
    - packs:/app/public/packs
    - rails_cache:/app/tmp/cache
    - .dockerdev/.bashrc:/root/.bashrc:ro
  environment:
    <<: *env
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    EDITOR: vi

services:
  backend:
    <<: *backend

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - "3000:3000"
      - "3002:3002"

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules:cached
      - packs:/app/public/packs
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  bundle:
  node_modules:
  rails_cache:
  packs:
